# Generated by Django 4.2.11 on 2024-05-03 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="идентификатор сессии",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[("transfer", "перевод"), ("cash", "наличные")],
                max_length=35,
                null=True,
                verbose_name="метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
