# Generated by Django 4.2.11 on 2024-05-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment_session_id_payment_url_alter_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="идентификатор продукта",
            ),
        ),
    ]
