# Generated by Django 4.2.11 on 2024-05-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="updated_at",
        ),
    ]
