# Generated by Django 4.2.11 on 2024-05-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_remove_subscription_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
    ]
